;;; package -- Summary
;;; Commentary:
;;; Code:

;; themes

;; (load-theme 'tango t)

;; TODO: load them according daylight and daynight
;; (use-package monokai-theme
;;   :ensure t
;;   ;; :config
;;   ;; (load-theme 'monokai t)
;;   )

(use-package theme-changer
  :ensure t
  :init
  (setq calendar-location-name "Beijing, CN")
  (setq calendar-latitude 39.905)
  (setq calendar-longitude 116.39139)
  :config
  (change-theme 'tango 'monokai))

;; font installation and configuration

;; FiraCode: https://github.com/tonsky/FiraCode/wiki/Installing

;; simusun-extb: https://www.dafontfree.net/freefonts-simsun-extb-f58270.htm

;; FreeBSD & linux installation
;; mkdir -p ~/.fonts/extb && cp simsunb.ttf ~/.fonts/extb/

;; 更改显示字体大小 16pt
;; http://stackoverflow.com/questions/294664/how-to-set-the-font-size-in-emacs
;; (set-face-attribute 'default nil
;;                     :height 160)

(use-package cnfonts
  :ensure t
  :config
  (cnfonts-enable))

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
;; (set-face-attribute
;;  'default nil
;;  :font (font-spec :name "-*-Fira Code-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1"
;;                   :weight 'normal
;;                   :slant 'normal
;;                   :size 12.5))
;; (dolist (charset '(kana han symbol cjk-misc bopomofo))
;;   (if (display-graphic-p)
;;       ;; Fontset ‘tty’ does not exist
;;       (progn
;;         (set-fontset-font
;;          (frame-parameter nil 'font)
;;          charset
;;          (font-spec :name "-*-STKaiti-normal-normal-normal-*-*-*-*-*-p-0-iso10646-1"
;;                     :weight 'normal
;;                     :slant 'normal
;;                     :size 14.5)))))

(provide 'abel-theme)

;;; abel-theme.el ends here
